services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # TODO:8080が多そうなので変える
    ports:
      - "5000:5000"
    tty: true
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
