import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useEffect, useState } from "react";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });
export default function Home() {
  const [message, setMessage] = useState("");

  useEffect(() => {
    const fetchText = async () => {
      try {
        const response = await axios.get("http://localhost:8080/hello");
        setMessage(response.data);
      } catch (error) {
        throw new Error("Error: ", error);
      }
    };

    fetchText();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>{message}</main>
    </>
  );
}
