import Head from "next/head";
import { Inter } from "next/font/google";
import { useEffect, useState } from "react";
import axios from "axios";
import Link from "next/link";
import { SubmitHandler, useForm } from "react-hook-form";

const inter = Inter({ subsets: ["latin"] });
export default function Home() {
  const [todos, setTodos] = useState([]);

  // TODO:ここもawaitにすべきかもしれないが単純につけるだけだとだめそうので調べる
  useEffect(() => {
    fetchTodos();
  }, []);

  const fetchTodos = async () => {
    try {
      const res = await axios.get("http://localhost:8080/todos");
      setTodos(res.data);
    } catch (error) {
      console.error(error);
    }
  };

  const addTodo = async (data) => {
    const { title, body } = data;
    try {
      await axios.post("http://localhost:8080/todo", {
        title,
        body,
      });
    } catch (error) {
      console.error(error);
    }
    await fetchTodos();
    reset();
  };

  type Inputs = {
    title: string;
    body: string;
  };

  const handleDelete = async (id: string) => {
    try {
      await axios.delete(`http://localhost:8080/todo/${id}`);
    } catch (error) {
      console.error(error);
    }
    await fetchTodos();
  };

  const {
    register,
    handleSubmit,
    formState: { errors },
    reset,
  } = useForm<Inputs>();
  const onSubmit: SubmitHandler<Inputs> = async (data) => await addTodo(data);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-200">
        <h1 className="text-3xl font-bold underline">TodoList</h1>
        <form onSubmit={handleSubmit(onSubmit)}>
          <label htmlFor="title" className="text-red-600">
            Title
          </label>
          <input
            {...register("title", {
              required: "this field is required.",
            })}
          />
          {errors.title && <span>{errors.title.message}</span>}
          <label htmlFor="body">Body</label>
          <input
            {...register("body", { required: "this field is required." })}
          />
          {errors.body && <span>{errors.body.message}</span>}
          <input type="submit" value="add" />
        </form>
        {todos.map((todo) => (
          <p key={todo.id}>
            {todo.title}, {todo.body}
            <button onClick={() => handleDelete(todo.id)}>delete</button>
            <Link href={`/todos/${todo.id}`}>detail</Link>
          </p>
        ))}
      </main>
    </>
  );
}
