FROM golang:1.22

WORKDIR /app

RUN apt-get update && \
    apt-get install -y \
        git \
        build-essential

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./

RUN go mod download

COPY . .

CMD ["air", "-c", ".air.toml"]